# Generated by Django 6.0 on 2025-12-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='follow_up',
            field=models.CharField(choices=[('pharmacy', 'Pharmacy'), ('lab', 'Laboratory'), ('radiology', 'Radiology'), ('billing', 'Billing')], default='billing', max_length=20),
        ),
    ]
