# Generated by Django 6.0 on 2025-12-14 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('triage', 'In Triage'), ('consultation', 'In Consultation'), ('lab', 'In Laboratory'), ('radiology', 'In Radiology'), ('pharmacy', 'In Pharmacy'), ('billing', 'In Billing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('insurance', 'Insurance')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
        ),
    ]
