# Generated by Django 6.0 on 2025-12-16 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_gender'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
